version: '3'
networks:
  laravel:

services:
  nginx:
    depends_on:
      - php
      - mongodb
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "8090:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  php:
    build:
      context: '.'
      dockerfile: DockerFile
    links:
      - mongodb
    container_name: php
    volumes:
       - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  mongodb:
    image : mongo:4.4.18
    container_name: mongodb
    env_file:
             - docker.env
    restart: unless-stopped
    volumes: 
      #- ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /data/db
    ports:
      - 27018:27017 
    networks:
      - laravel
    command: mongod
